spring:
    application:
        name: test_review
    datasource:
        url: jdbc:h2:tcp://localhost/~/testApi
        driver-class-name: org.h2.Driver
        username: sa
    jpa:
        hibernate:
            ddl-auto: create    # update
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        org.hibernate.SQL: debug  # Hibernate SQL ?? ?? ???
        org.hibernate.orm.jdbc.bind: trace  # Hibernate 6?? ???? ??
